name: build

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        mode: [debug, release]
    outputs:
      matrix-os: ${{ matrix.os }}
      matrix-mode: ${{ matrix.mode }}
    steps:
    - uses: actions/checkout@v4
    - name: setup msvc
      if: matrix.os == 'windows-latest'
      uses: TheMrMilchmann/setup-msvc-dev@v3.0.1
      with:
        arch: x64
    - uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
    - name: build if windows
      if: matrix.os == 'windows-latest'
      run: |
        xmake f -p windows -a x64 -m ${{ matrix.mode }}
        xmake b -a
    - name: build if linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        xmake f -p linux -a x64 -m ${{ matrix.mode }}
        xmake b -a
    - name: upload if windows
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: main_windows_${{ matrix.mode }}
        path: .\build\windows\x64\${{ matrix.mode }}\main.exe
    - name: upload if linux
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: main_linux_${{ matrix.mode }}
        path: ./build/linux/x64/${{ matrix.mode }}/main
  run:
    needs: [build]
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        mode: [debug, release]
    runs-on: ${{ needs.build.outputs.matrix-os }}
    steps:
      - name: download if windows
        if: needs.build.outputs.matrix-os == 'windows-latest'
        uses: actions/download-artifact@v4
        with:
          name: main_windows_${{ needs.build.outputs.matrix-mode }}
      - name: download if linux
        if: needs.build.outputs.matrix-os == 'ubuntu-latest'
        uses: actions/download-artifact@v4
        with:
          name: main_linux_${{ needs.build.outputs.matrix-mode }}
      - name: run if windows
        if: needs.build.outputs.matrix-os == 'windows-latest'
        run: .\main.exe
      - name: run if linux
        if: needs.build.outputs.matrix-os == 'ubuntu-latest'
        run: |
          chmod 744 ./main
          ./main
  valgrind:
    if: needs.build.outputs.matrix-os == 'ubuntu-latest'
    needs: [build]
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        mode: [debug, release]
    runs-on: ${{ needs.build.outputs.matrix-os }}
    steps:
      - name: download if linux
        if: needs.build.outputs.matrix-os == 'ubuntu-latest'
        uses: actions/download-artifact@v4
        with:
          name: main_linux_${{ needs.build.outputs.matrix-mode }}
      - name: chmod 744
        if: needs.build.outputs.matrix-os == 'ubuntu-latest'
        run: |
          chmod 744 ./main
      - name: valgrind if linux
        if: needs.build.outputs.matrix-os == 'ubuntu-latest'
        uses: Ximaz/valgrind-action@v1.2.0
        with:
          binary_path: ./main
