name: build

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v4
    - name: setup msvc
      if: matrix.os == 'windows-latest'
      uses: TheMrMilchmann/setup-msvc-dev@v3.0.1
      with:
        arch: x64
    - uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
    - name: build with xmake
      run: |
        xmake f -p linux -a x64 -m release
        xmake b
        xmake r
