name: valgrind

on: push

jobs:
  valgrind:
    runs-on: ubuntu-latest
    steps:
      - name: print pwd
        run: |
          pwd
    # - uses: Ximaz/valgrind-action@v1.2.0
      # with:
        # binary_path: "./build/linux/x64/release/main"
